# Generated by Django 2.2.4 on 2019-08-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('NORM', 'normal'), ('CLST', 'classteacher')], default='NORM', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Teacher'),
        ),
    ]
