# Generated by Django 2.2.4 on 2019-08-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20190813_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_last_name',
            new_name='last_name',
        ),
    ]
