# Generated by Django 2.2.4 on 2019-08-23 11:45

from django.db import migrations

def forwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20190814_0755'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
