# Generated by Django 2.2.4 on 2019-08-26 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20190823_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('head', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quickstart.Teacher')),
                ('branch_name', models.CharField(choices=[('CS', 'computer'), ('ELEC', 'electronic')], default='CS', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quickstart.Department'),
            preserve_default=False,
        ),
    ]
