# Generated by Django 2.2.4 on 2019-08-26 12:41

from django.db import migrations

def forwards(apps, schema_editor):
    Student = apps.get_model('quickstart', 'Student')
    Department = apps.get_model('quickstart', 'Department')
    Teacher = apps.get_model('quickstart', 'Teacher')

    Student.objects.filter(age__range=[0,20]).update(age=20)
    Student.objects.filter(age__range=[40,100]).update(age=40)

    for student in Student.objects.all():
        if Student.objects.filter(roll_no=student.roll_no).count()>1:
            student.delete()

    for department in Department.objects.all():
        if Department.objects.filter(branch_name=department.branch_name).count()>1:
            department.delete() 

    for teacher in Teacher.objects.all():
        if Teacher.objects.filter(subject=teacher.subject).count()>1:
            teacher.delete()               

class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_auto_20190826_0701'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
