# Generated by Django 2.2.4 on 2019-08-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20190826_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=20)),
                ('marks', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='sec',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='branch_name',
            field=models.CharField(choices=[('CS', 'computer'), ('ELEC', 'electronic')], default='CS', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=50, unique=True),
        ),
       
    ]
